Avoid bundling ol imports into the final build
jonataswalker/ol-contextmenu pull request #272
Opened 2023-09-14 08:43 UTC by menghany

2023-09-14 16:48 UTC, jonataswalker commented
This is great but the `iife` bundle have some problems.

You'll see if you run `examples/contextmenu.html`. Making some tests it looks like that this change can fix it:

```javascript
rollupOptions: {
    external: [/^ol.*/],
    output: {
        globals: {
            'ol/MapBrowserEvent': 'ol.MapBrowserEvent',
            'ol/control/Control': 'ol.control.Control',
        },
        assetFileNames: () => 'ol-contextmenu.css',
    },
},
```

2023-09-14 16:54 UTC, jonataswalker requested changes

2023-09-14 16:54 UTC, jonataswalker commented on vite.config.ts
> +                      external: ['vue', /^ol.*/],
`'vue'` here is not necessary, right?

2023-09-14 16:54 UTC, jonataswalker commented on vite.config.ts
> +                              'ol/MapBrowserEvent': 'MapBrowserEvent',
`'ol/MapBrowserEvent': 'ol.MapBrowserEvent'`

not tested with examples that import `ol-contextmenu`, could you do that, please?

2023-09-14 16:54 UTC, jonataswalker commented on vite.config.ts
> +                              'ol/control/Control': 'Control',
`'ol/control/Control': 'ol.control.Control'`

2023-09-15 02:07 UTC, menghany commented on vite.config.ts
> +                      external: ['vue', /^ol.*/],
Sorry, I forgot to delete my test code.

2023-09-15 02:08 UTC, menghany commented on vite.config.ts
> +                      external: ['vue', /^ol.*/],
Sorry, I forgot to delete my test code.

2023-09-19 19:58 UTC, jonataswalker approved these changes

2023-09-19 19:58 UTC, merged